"""Per-stock Direction/Target for the EMA Confluence Breakout strategy — the
single source of truth shared by the backtest routes (app/routes/api.py), the
form (backtest.js) and the LIVE algo
(algo/ema_confluence/ema_confluence_algo.py, which scans every key here).

direction: 'long' (BUY Only), 'short' (Sell Only) or 'both'. target_pct is the
Target % field (min 1%, see EmaPullbackEngine).

This table is the WHOLE universe, not a set of overrides: a symbol that is not
a key here is not an EMA Confluence symbol at all, and nothing anywhere
invents a default for one. The backtest route rejects it, the form says so
rather than pre-filling Both/5%, and the live algo never scans it. That used
to be a silent fallback, which meant a typo'd or delisted ticker ran a
backtest on made-up parameters and read as a real result.

Order below is the user-supplied order (indices first, then alphabetical).
"""

EMA_SYMBOL_DEFAULTS = {
    'NIFTY':        {'direction': 'long', 'target_pct': 7},
    'BANKNIFTY':    {'direction': 'both', 'target_pct': 8},
    'SENSEX':       {'direction': 'both', 'target_pct': 2.5},
    'SBIN':         {'direction': 'long', 'target_pct': 3},
    'HDFCBANK':     {'direction': 'short', 'target_pct': 10},
    '360ONE':       {'direction': 'long', 'target_pct': 2},
    'ABB':          {'direction': 'long', 'target_pct': 15},
    'ABCAPITAL':    {'direction': 'long', 'target_pct': 4},
    'ADANIENSOL':   {'direction': 'long', 'target_pct': 15},
    'ADANIENT':     {'direction': 'short', 'target_pct': 7},
    'ADANIGREEN':   {'direction': 'both', 'target_pct': 3},
    'ADANIPORTS':   {'direction': 'both', 'target_pct': 8},
    'ADANIPOWER':   {'direction': 'long', 'target_pct': 12},
    'AMBER':        {'direction': 'long', 'target_pct': 15},
    'AMBUJACEM':    {'direction': 'both', 'target_pct': 12},
    'ANGELONE':     {'direction': 'long', 'target_pct': 6},
    'APLAPOLLO':    {'direction': 'long', 'target_pct': 3},
    'APOLLOHOSP':   {'direction': 'long', 'target_pct': 15},
    'ASHOKLEY':     {'direction': 'long', 'target_pct': 15},
    'ASTRAL':       {'direction': 'both', 'target_pct': 12},
    'AUBANK':       {'direction': 'both', 'target_pct': 2},
    'AXISBANK':     {'direction': 'long', 'target_pct': 8},
    'BAJAJFINSV':   {'direction': 'both', 'target_pct': 15},
    'BAJAJHLDNG':   {'direction': 'long', 'target_pct': 15},
    'BAJFINANCE':   {'direction': 'short', 'target_pct': 7},
    'BANDHANBNK':   {'direction': 'short', 'target_pct': 4},
    'BDL':          {'direction': 'long', 'target_pct': 15},
    'BHARTIARTL':   {'direction': 'long', 'target_pct': 15},
    'BIOCON':       {'direction': 'both', 'target_pct': 15},
    'BOSCHLTD':     {'direction': 'both', 'target_pct': 12},
    'BPCL':         {'direction': 'long', 'target_pct': 15},
    'BRITANNIA':    {'direction': 'both', 'target_pct': 15},
    'CDSL':         {'direction': 'short', 'target_pct': 15},
    'CAMS':         {'direction': 'both', 'target_pct': 4},
    'COALINDIA':    {'direction': 'short', 'target_pct': 2.5},
    'COCHINSHIP':   {'direction': 'long', 'target_pct': 15},
    'COFORGE':      {'direction': 'long', 'target_pct': 10},
    'COLPAL':       {'direction': 'long', 'target_pct': 5},
    'CROMPTON':     {'direction': 'both', 'target_pct': 8},
    'DALBHARAT':    {'direction': 'short', 'target_pct': 8},
    'DELHIVERY':    {'direction': 'short', 'target_pct': 2.5},
    'DMART':        {'direction': 'long', 'target_pct': 5},
    'EICHERMOT':    {'direction': 'short', 'target_pct': 8},
    'ETERNAL':      {'direction': 'both', 'target_pct': 15},
    'FEDERALBNK':   {'direction': 'long', 'target_pct': 2.5},
    'GLENMARK':     {'direction': 'short', 'target_pct': 4},
    'GMRAIRPORT':   {'direction': 'long', 'target_pct': 12},
    'GODFRYPHLP':   {'direction': 'long', 'target_pct': 15},
    'GODREJPROP':   {'direction': 'long', 'target_pct': 4},
    'GRASIM':       {'direction': 'short', 'target_pct': 15},
    'HAVELLS':      {'direction': 'short', 'target_pct': 3.5},
    'HDFCAMC':      {'direction': 'short', 'target_pct': 15},
    'HDFCLIFE':     {'direction': 'both', 'target_pct': 3},
    'HINDUNILVR':   {'direction': 'both', 'target_pct': 12},
    'HINDZINC':     {'direction': 'short', 'target_pct': 3.5},
    'ICICIGI':      {'direction': 'long', 'target_pct': 10},
    'ICICIPRULI':   {'direction': 'short', 'target_pct': 3},
    'IDEA':         {'direction': 'both', 'target_pct': 15},
    'IDFCFIRSTB':   {'direction': 'short', 'target_pct': 10},
    'INDHOTEL':     {'direction': 'short', 'target_pct': 8},
    'INDIANB':      {'direction': 'short', 'target_pct': 5},
    'INDIGO':       {'direction': 'both', 'target_pct': 15},
    'INDUSINDBK':   {'direction': 'short', 'target_pct': 15},
    'INDUSTOWER':   {'direction': 'short', 'target_pct': 15},
    'IOC':          {'direction': 'both', 'target_pct': 12},
    'IRFC':         {'direction': 'long', 'target_pct': 5},
    'JINDALSTEL':   {'direction': 'long', 'target_pct': 15},
    'JSWSTEEL':     {'direction': 'long', 'target_pct': 12},
    'JUBLFOOD':     {'direction': 'long', 'target_pct': 8},
    'KALYANKJIL':   {'direction': 'both', 'target_pct': 12},
    'KEI':          {'direction': 'long', 'target_pct': 15},
    'KFINTECH':     {'direction': 'short', 'target_pct': 4},
    'LICHSGFIN':    {'direction': 'short', 'target_pct': 15},
    'LODHA':        {'direction': 'long', 'target_pct': 8},
    'LT':           {'direction': 'short', 'target_pct': 15},
    'LTF':          {'direction': 'both', 'target_pct': 12},
    'LTM':          {'direction': 'long', 'target_pct': 15},
    'M&M':          {'direction': 'both', 'target_pct': 15},
    'MANAPPURAM':   {'direction': 'long', 'target_pct': 10},
    'MANKIND':      {'direction': 'both', 'target_pct': 5},
    'MCX':          {'direction': 'short', 'target_pct': 4},
    'MOTHERSON':    {'direction': 'long', 'target_pct': 15},
    'MUTHOOTFIN':   {'direction': 'both', 'target_pct': 12},
    'NAUKRI':       {'direction': 'both', 'target_pct': 15},
    'NBCC':         {'direction': 'long', 'target_pct': 15},
    'NESTLEIND':    {'direction': 'long', 'target_pct': 15},
    'NMDC':         {'direction': 'both', 'target_pct': 7},
    'OFSS':         {'direction': 'long', 'target_pct': 4},
    'OIL':          {'direction': 'both', 'target_pct': 8},
    'ONGC':         {'direction': 'both', 'target_pct': 8},
    'PAGEIND':      {'direction': 'long', 'target_pct': 10},
    'PAYTM':        {'direction': 'both', 'target_pct': 6},
    'PETRONET':     {'direction': 'short', 'target_pct': 12},
    'PFC':          {'direction': 'long', 'target_pct': 15},
    'PNB':          {'direction': 'both', 'target_pct': 15},
    'PNBHOUSING':   {'direction': 'long', 'target_pct': 8},
    'POWERGRID':    {'direction': 'short', 'target_pct': 10},
    'PREMIERENE':   {'direction': 'short', 'target_pct': 3},
    'PRESTIGE':     {'direction': 'both', 'target_pct': 12},
    'RADICO':       {'direction': 'long', 'target_pct': 15},
    'RBLBANK':      {'direction': 'both', 'target_pct': 15},
    'RECLTD':       {'direction': 'short', 'target_pct': 12},
    'RVNL':         {'direction': 'both', 'target_pct': 15},
    'SAMMAANCAP':   {'direction': 'both', 'target_pct': 5},
    'SBICARD':      {'direction': 'short', 'target_pct': 15},
    'SBILIFE':      {'direction': 'long', 'target_pct': 15},
    'SHREECEM':     {'direction': 'long', 'target_pct': 12},
    'SHRIRAMFIN':   {'direction': 'short', 'target_pct': 6},
    'SOLARINDS':    {'direction': 'both', 'target_pct': 10},
    'SONACOMS':     {'direction': 'long', 'target_pct': 15},
    'SRF':          {'direction': 'long', 'target_pct': 6},
    'SUNPHARMA':    {'direction': 'long', 'target_pct': 15},
    'SUPREMEIND':   {'direction': 'short', 'target_pct': 15},
    'SUZLON':       {'direction': 'both', 'target_pct': 8},
    'TATACONSUM':   {'direction': 'long', 'target_pct': 7},
    'TATAELXSI':    {'direction': 'short', 'target_pct': 15},
    'TATAPOWER':    {'direction': 'long', 'target_pct': 5},
    'TATASTEEL':    {'direction': 'short', 'target_pct': 15},
    'TCS':          {'direction': 'short', 'target_pct': 15},
    'TECHM':        {'direction': 'long', 'target_pct': 15},
    'TIINDIA':      {'direction': 'short', 'target_pct': 15},
    'TITAN':        {'direction': 'both', 'target_pct': 10},
    'TMPV':         {'direction': 'short', 'target_pct': 4},
    'TRENT':        {'direction': 'long', 'target_pct': 10},
    'TVSMOTOR':     {'direction': 'long', 'target_pct': 10},
    'ULTRACEMCO':   {'direction': 'both', 'target_pct': 8},
    'UNIONBANK':    {'direction': 'long', 'target_pct': 15},
    'UPL':          {'direction': 'short', 'target_pct': 6},
    'VOLTAS':       {'direction': 'long', 'target_pct': 8},
    'WAAREEENER':   {'direction': 'both', 'target_pct': 12},
    'WIPRO':        {'direction': 'short', 'target_pct': 4},
    'YESBANK':      {'direction': 'both', 'target_pct': 2},
    'ZYDUSLIFE':    {'direction': 'both', 'target_pct': 8},
}
