"""Per-stock default combo for the 30-Min Opening Fakeout strategy — the
single source of truth shared by the backtest routes (app/routes/api.py),
the optimizer, and the live algo (algo/thirty_min_fakeout/tmf_algo.py).
Kept dependency-light (no Flask/app imports) so the live algo module can
import it without any risk of a circular import back through api.py.
"""

# No broker exposes *historical* per-stock MIS leverage (only today's live
# value), so a single assumed multiplier is applied uniformly to every
# stock, for both backtest sizing and live order sizing. 5x matches
# Zerodha's typical MIS leverage for liquid F&O-eligible large/mid-caps —
# an approximation, not the real historical (or even necessarily current)
# leverage for every stock/day.
TMF_EQUITY_LEVERAGE = 5

# Per-stock default combo (direction + the 3 filter toggles) — the
# best-known settings for each stock, found by running "Find Best Params"
# one stock at a time. Used as the default filter set for that stock's
# scan instead of one combo applied uniformly to every stock; a stock
# missing here falls back to whatever the request's global direction/
# filter fields say. See run_thirty_min_fakeout_backtest_api's
# use_symbol_defaults flag.
TMF_SYMBOL_DEFAULTS = {
    '360ONE': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': True},
    'ADANIENSOL': {'direction': 'short', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': False},
    'ADANIENT': {'direction': 'short', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': True},
    'ADANIPORTS': {'direction': 'short', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': True},
    'ADANIPOWER': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'ALKEM': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'AMBUJACEM': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': False},
    'ANGELONE': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': False},
    'APOLLOHOSP': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': True},
    'ASHOKLEY': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': False},
    'ASIANPAINT': {'direction': 'long', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': True},
    'ASTRAL': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': True},
    'AUROPHARMA': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': True},
    'BAJAJ-AUTO': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': False},
    'BAJAJFINSV': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': True},
    'BAJAJHLDNG': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': False},
    'BAJFINANCE': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': False},
    'BANDHANBNK': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'BANKBARODA': {'direction': 'long', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'BANKINDIA': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': True},
    'BDL': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'BHARATFORG': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': True},
    'BHARTIARTL': {'direction': 'short', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': False},
    'BHEL': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': False},
    'BOSCHLTD': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': False},
    'BPCL': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'CANBK': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'CDSL': {'direction': 'short', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'CGPOWER': {'direction': 'long', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'CHOLAFIN': {'direction': 'short', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': False},
    'COCHINSHIP': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': False},
    'COLPAL': {'direction': 'short', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': False},
    'CONCOR': {'direction': 'short', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': False},
    'CROMPTON': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': True},
    'CUMMINSIND': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': False},
    'DABUR': {'direction': 'short', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'DALBHARAT': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'DIVISLAB': {'direction': 'short', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': False},
    'DIXON': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'DLF': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'DRREDDY': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': False},
    'EICHERMOT': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': False},
    'EXIDEIND': {'direction': 'short', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'FEDERALBNK': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'FORCEMOT': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'GAIL': {'direction': 'short', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': False},
    'GLENMARK': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': True},
    'GODREJCP': {'direction': 'long', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': True},
    'GODREJPROP': {'direction': 'short', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': False},
    'GRASIM': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'GVT&D': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'HAL': {'direction': 'short', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': False},
    'HAVELLS': {'direction': 'short', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': False},
    'HCLTECH': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': False},
    'HDFCAMC': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'HDFCBANK': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': True},
    'HEROMOTOCO': {'direction': 'long', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': True},
    'HINDALCO': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'HINDPETRO': {'direction': 'long', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': True},
    'ICICIGI': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': False},
    'IDEA': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': False},
    'IDFCFIRSTB': {'direction': 'short', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': True},
    'INDHOTEL': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'INDIANB': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': True},
    'INDIGO': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': True},
    'INDUSINDBK': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': False},
    'IOC': {'direction': 'short', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': True},
    'JINDALSTEL': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'JIOFIN': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': False},
    'JSWSTEEL': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': True},
    'KAYNES': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'KEI': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'KFINTECH': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': False},
    'KPITTECH': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': True},
    'LICI': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': True},
    'LODHA': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': True},
    'LT': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'LTF': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': False},
    'LTM': {'direction': 'long', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': True},
    'LUPIN': {'direction': 'long', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': False},
    'M&M': {'direction': 'short', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': False},
    'MANAPPURAM': {'direction': 'short', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'MANKIND': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': True},
    'MARICO': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'MARUTI': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': False},
    'MAZDOCK': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': False},
    'MCX': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'MFSL': {'direction': 'long', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': False},
    'MOTHERSON': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': True},
    'MOTILALOFS': {'direction': 'long', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': True},
    'MPHASIS': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': True},
    'MUTHOOTFIN': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': False},
    'NAM-INDIA': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'NATIONALUM': {'direction': 'short', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': False},
    'NAUKRI': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': True},
    'NBCC': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': True},
    'NESTLEIND': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': True},
    'NMDC': {'direction': 'short', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': True},
    'NTPC': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': False},
    'NYKAA': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': False},
    'OBEROIRLTY': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': False},
    'OIL': {'direction': 'long', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'ONGC': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': False},
    'PERSISTENT': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': True},
    'PETRONET': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': True},
    'PFC': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': False},
    'PGEL': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': False},
    'PHOENIXLTD': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': False},
    'PIDILITIND': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'PIIND': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': True},
    'POLYCAB': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': False},
    'POWERINDIA': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'PRESTIGE': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'RADICO': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': False},
    'RBLBANK': {'direction': 'long', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': False},
    'RECLTD': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': False},
    'RVNL': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'SAIL': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': False},
    'SAMMAANCAP': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'SBICARD': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': False},
    'SBILIFE': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': False},
    'SBIN': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'SHREECEM': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': False},
    'SIEMENS': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'SOLARINDS': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': True},
    'SRF': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'SUNPHARMA': {'direction': 'short', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': True},
    'TATACONSUM': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': False},
    'TECHM': {'direction': 'long', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'TIINDIA': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': False},
    'TMPV': {'direction': 'short', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': False},
    'TORNTPHARM': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'TRENT': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': False},
    'TVSMOTOR': {'direction': 'short', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': False},
    'ULTRACEMCO': {'direction': 'short', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'UNIONBANK': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': False},
    'UNITDSPR': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': True, 'use_c2_close_filter': False},
    'UNOMINDA': {'direction': 'long', 'use_entry_buffer': True, 'use_body_filter': True, 'use_c2_close_filter': False},
    'UPL': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'VBL': {'direction': 'long', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': False},
    'VOLTAS': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': True},
    'YESBANK': {'direction': 'both', 'use_entry_buffer': True, 'use_body_filter': False, 'use_c2_close_filter': True},
    'ZYDUSLIFE': {'direction': 'both', 'use_entry_buffer': False, 'use_body_filter': False, 'use_c2_close_filter': False},
}

# The 30-Min Fakeout scan's stock universe is this fixed, user-supplied
# list — not every F&O stock (_fo_futures_universe) like other strategies.
# Both the "All Stocks" scan and the "Find Best Params" optimizer sweep
# only these symbols, and the single-symbol dropdown only offers these.
TMF_STOCK_UNIVERSE = sorted(TMF_SYMBOL_DEFAULTS.keys())
