"""ICICI Direct (Breeze) security master — NSE symbols → Breeze stock codes.

Breeze does not address instruments by symbol. Every data call is keyed by
(stock_code, exchange_code, product_type, expiry_date, right, strike_price),
and its stock_code vocabulary is ICICI's own: RELIANCE is 'RELIND', BANKNIFTY
is 'CNXBAN', SENSEX is 'BSESEN'. Nothing in the rest of the app speaks that
vocabulary, so this module downloads ICICI's public security master and builds
the translation table from it.

    https://directlink.icicidirect.com/NewSecurityMaster/SecurityMaster.zip

Public, no auth, ~2.2 MB, regenerated by ICICI each morning (~07:00 IST) —
the same shape of dependency the Fyers adapter already has on
public.fyers.in/sym_details/*.csv.

Files in the zip, and the columns this module reads (quoted CSV, header row):

    NSEScripMaster.txt    cash NSE   ShortName, ExchangeCode(last), Lotsize
    BSEScripMaster.txt    cash BSE   same
    FONSEScripMaster.txt  NSE F&O    InstrumentName, ShortName, ExpiryDate,
                                     StrikePrice, OptionType, LotSize(col 28),
                                     ExchangeCode(last)
    FOBSEScripMaster.txt  BSE F&O    same layout as FONSE

ExchangeCode is the exchange's own trading symbol ('RELIANCE', 'NIFTY 50');
ShortName is what Breeze wants ('RELIND', 'NIFTY'). Index rows in the cash
masters carry the index name in Token ('NIFTY 50'), not a numeric token.

The parsed table is cached in memory for the process and on disk under
.cache/icici_security_master.json so a restart does not re-download 2.2 MB.
"""

import csv
import io
import json
import logging
import os
import threading
import zipfile
from datetime import date, datetime
from typing import Dict, List, Optional, Tuple

import requests

logger = logging.getLogger(__name__)

MASTER_URL = "https://directlink.icicidirect.com/NewSecurityMaster/SecurityMaster.zip"

_CACHE_FILE = os.path.join(os.path.dirname(__file__), "..", ".cache",
                           "icici_security_master.json")

# ICICI regenerates the zip each morning; a day-old table is stale only for
# instruments listed today, so refresh once per calendar day.
_REFRESH_SECONDS = 6 * 3600

_lock = threading.Lock()
_TABLE: Optional[Dict] = None
_LOADED_AT: Optional[datetime] = None

# Which master file backs which Breeze exchange_code.
_FILES = {
    'NSE': 'NSEScripMaster.txt',
    'BSE': 'BSEScripMaster.txt',
    'NFO': 'FONSEScripMaster.txt',
    'BFO': 'FOBSEScripMaster.txt',
}

# Index roots as the rest of the app names them (Fyers/Kite naming) → the
# ExchangeCode ICICI files them under. Everything else resolves by exact
# ExchangeCode match, so only the indices need spelling out.
_INDEX_EXCHANGE_CODES = {
    'NIFTY':        'NIFTY 50',
    'NIFTY50':      'NIFTY 50',
    'BANKNIFTY':    'NIFTY BANK',
    'NIFTYBANK':    'NIFTY BANK',
    'FINNIFTY':     'NIFTY FINANCIAL',
    'MIDCPNIFTY':   'NIFTY MIDCAP',
    'NIFTYNXT50':   'NIFTY NEXT 50',
    'NIFTYMIDCAP150': 'NIFTY FPI 150',
    'SENSEX':       'SENSEX',
    'BANKEX':       'BANKEX',
    'INDIAVIX':     'INDVIX',
}

# Last-resort codes for the roots above, used when the master download fails
# and no disk cache exists. Verified against the 2026-09-02 master.
_INDEX_FALLBACK_CODES = {
    'NIFTY': 'NIFTY',
    'NIFTY50': 'NIFTY',
    'BANKNIFTY': 'CNXBAN',
    'NIFTYBANK': 'CNXBAN',
    'FINNIFTY': 'NIFFIN',
    'MIDCPNIFTY': 'NIFSEL',
    'NIFTYNXT50': 'NIFNEX',
    'NIFTYMIDCAP150': 'NIF150',
    'SENSEX': 'BSESEN',
    'BANKEX': 'BANKEX',
    'INDIAVIX': 'INDVIX',
}


def _rows(text: str):
    """Yield each master row as a dict keyed by its header name.

    The cash masters write their header as '"Token", "ShortName", ...' — a
    space after every comma — so skipinitialspace is required or every key
    but the first keeps a leading space.
    """
    reader = csv.reader(io.StringIO(text), skipinitialspace=True)
    try:
        header = [h.strip() for h in next(reader)]
    except StopIteration:
        return
    for parts in reader:
        if not parts:
            continue
        yield dict(zip(header, parts))


def _parse_expiry(raw: str) -> Optional[date]:
    """'29-Sep-2026' → date(2026, 9, 29)."""
    raw = (raw or '').strip()
    if not raw:
        return None
    for fmt in ('%d-%b-%Y', '%d-%B-%Y', '%Y-%m-%d'):
        try:
            return datetime.strptime(raw, fmt).date()
        except ValueError:
            continue
    return None


def _parse_cash(text: str) -> Dict[str, Dict]:
    """ExchangeCode → {'stock_code', 'lot_size'} for one cash master."""
    out: Dict[str, Dict] = {}
    for row in _rows(text):
        code = (row.get('ExchangeCode') or '').strip()
        short = (row.get('ShortName') or '').strip()
        if not code or not short:
            continue
        try:
            lot = int(float(row.get('Lotsize') or row.get('LotSize') or 1))
        except (TypeError, ValueError):
            lot = 1
        # The masters carry delisted duplicates ('NA' company rows); the first
        # row for an ExchangeCode is the live one, so do not overwrite.
        out.setdefault(code.upper(), {'stock_code': short, 'lot_size': lot or 1})
    return out


def _parse_fno(text: str) -> Tuple[Dict[str, Dict], Dict[str, List[str]]]:
    """Parse one F&O master.

    Returns (codes, expiries):
        codes    ExchangeCode → {'stock_code', 'lot_size'}
        expiries stock_code   → sorted ISO date strings, ascending
    """
    codes: Dict[str, Dict] = {}
    expiries: Dict[str, set] = {}
    for row in _rows(text):
        short = (row.get('ShortName') or '').strip()
        code = (row.get('ExchangeCode') or '').strip()
        if not short:
            continue
        if code:
            try:
                lot = int(float(row.get('LotSize') or 0))
            except (TypeError, ValueError):
                lot = 0
            entry = codes.setdefault(code.upper(), {'stock_code': short, 'lot_size': lot})
            # Lot size is per-expiry in the master and 0 on some rows; keep the
            # first non-zero one rather than letting a blank row erase it.
            if not entry.get('lot_size') and lot:
                entry['lot_size'] = lot
        exp = _parse_expiry(row.get('ExpiryDate') or '')
        if exp:
            expiries.setdefault(short, set()).add(exp.isoformat())
    return codes, {k: sorted(v) for k, v in expiries.items()}


def _download() -> Dict[str, str]:
    """Fetch the zip and return {filename: text} for the masters we use."""
    logger.info("[IciciMaster] Downloading %s ...", MASTER_URL)
    resp = requests.get(MASTER_URL, timeout=120)
    resp.raise_for_status()
    wanted = set(_FILES.values())
    out: Dict[str, str] = {}
    with zipfile.ZipFile(io.BytesIO(resp.content)) as zf:
        for name in zf.namelist():
            base = os.path.basename(name)
            if base in wanted:
                out[base] = zf.read(name).decode('utf-8', errors='replace')
    logger.info("[IciciMaster] Extracted %d master files (%.1f MB zip)",
                len(out), len(resp.content) / 1e6)
    return out


def _build(files: Dict[str, str]) -> Dict:
    table: Dict[str, Dict] = {'codes': {}, 'expiries': {}, 'built_at': datetime.now().isoformat()}
    for exch, fname in _FILES.items():
        text = files.get(fname)
        if not text:
            continue
        if exch in ('NSE', 'BSE'):
            table['codes'][exch] = _parse_cash(text)
        else:
            codes, expiries = _parse_fno(text)
            table['codes'][exch] = codes
            table['expiries'][exch] = expiries
    return table


def _read_disk_cache() -> Optional[Dict]:
    try:
        if not os.path.exists(_CACHE_FILE):
            return None
        age = datetime.now().timestamp() - os.path.getmtime(_CACHE_FILE)
        if age > _REFRESH_SECONDS:
            return None
        with open(_CACHE_FILE, 'r') as fh:
            return json.load(fh)
    except Exception as exc:
        logger.warning("[IciciMaster] Disk cache unreadable: %s", exc)
        return None


def _write_disk_cache(table: Dict) -> None:
    try:
        os.makedirs(os.path.dirname(_CACHE_FILE), exist_ok=True)
        with open(_CACHE_FILE, 'w') as fh:
            json.dump(table, fh)
    except Exception as exc:
        logger.warning("[IciciMaster] Could not write disk cache: %s", exc)


def load(force: bool = False) -> Dict:
    """Return the parsed master, downloading it at most once per _REFRESH_SECONDS."""
    global _TABLE, _LOADED_AT
    with _lock:
        fresh = (_TABLE is not None and _LOADED_AT is not None
                 and (datetime.now() - _LOADED_AT).total_seconds() < _REFRESH_SECONDS)
        if fresh and not force:
            return _TABLE

        if not force:
            cached = _read_disk_cache()
            if cached:
                _TABLE, _LOADED_AT = cached, datetime.now()
                return _TABLE

        try:
            table = _build(_download())
            if table['codes']:
                _TABLE, _LOADED_AT = table, datetime.now()
                _write_disk_cache(table)
                return _TABLE
        except Exception as exc:
            logger.error("[IciciMaster] Download/parse failed: %s", exc)

        # Serve whatever we already have — a stale table still translates every
        # instrument that existed yesterday, which is all of them but today's
        # new listings. Only if there is nothing at all do we fall back to the
        # hardcoded index codes, which keep the index option chains working.
        if _TABLE is None:
            stale = _read_disk_cache()
            if stale is None and os.path.exists(_CACHE_FILE):
                try:
                    with open(_CACHE_FILE, 'r') as fh:
                        stale = json.load(fh)
                except Exception:
                    stale = None
            _TABLE = stale or {'codes': {}, 'expiries': {}, 'built_at': None}
            _LOADED_AT = datetime.now()
        return _TABLE


def stock_code(root: str, exchange_code: str) -> Optional[str]:
    """Breeze stock_code for an app-side root ('RELIANCE', 'BANKNIFTY').

    exchange_code is Breeze's: NSE/BSE for cash, NFO/BFO for derivatives.
    """
    if not root:
        return None
    root_u = root.strip().upper()
    table = load()
    codes = (table.get('codes') or {}).get(exchange_code.upper(), {})

    # Index roots are filed under a spelled-out ExchangeCode ('NIFTY BANK'),
    # never under the app's own name for them ('BANKNIFTY').
    alias = _INDEX_EXCHANGE_CODES.get(root_u.replace(' ', ''))
    if alias and alias.upper() in codes:
        return codes[alias.upper()]['stock_code']

    if root_u in codes:
        return codes[root_u]['stock_code']

    # Some index names reach us already spelled out ('NIFTY 50').
    if root_u.replace(' ', '') in {k.replace(' ', '') for k in codes}:
        for k, v in codes.items():
            if k.replace(' ', '') == root_u.replace(' ', ''):
                return v['stock_code']

    if alias is None and root_u.replace(' ', '') in _INDEX_FALLBACK_CODES:
        return _INDEX_FALLBACK_CODES[root_u.replace(' ', '')]
    if alias is not None:
        fallback = _INDEX_FALLBACK_CODES.get(root_u.replace(' ', ''))
        if fallback:
            logger.warning("[IciciMaster] %s not in %s master — using fallback code %s",
                           root_u, exchange_code, fallback)
            return fallback

    logger.warning("[IciciMaster] No ICICI stock_code for root=%s exchange=%s",
                   root_u, exchange_code)
    return None


def lot_size(root: str, exchange_code: str) -> Optional[int]:
    """Contract lot size from the master, or None when unknown."""
    root_u = (root or '').strip().upper()
    codes = (load().get('codes') or {}).get(exchange_code.upper(), {})
    alias = _INDEX_EXCHANGE_CODES.get(root_u.replace(' ', ''), root_u)
    entry = codes.get(alias.upper()) or codes.get(root_u)
    if entry and entry.get('lot_size'):
        return int(entry['lot_size'])
    return None


def expiries(code: str, exchange_code: str = 'NFO') -> List[str]:
    """Every listed expiry for a Breeze stock_code, ascending ISO dates."""
    table = load().get('expiries') or {}
    return list((table.get(exchange_code.upper()) or {}).get(code, []))
